## to begin Dockerized database, type 'docker compose up -d'

version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"